openapi: 3.0.1
info:
  version: v1
  title: Disco API
  contact:
    name: Disco Team
    email: ask@disco.xyz
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Forbidden:
      type: object
      properties:
        name:
          type: string
          description: The error name
          minLength: 1
          example: FORBIDDEN
          default: FORBIDDEN
        message:
          type: string
          description: An error message
          minLength: 1
        status:
          type: number
          description: The status code of the exception
          example: 403
          default: 403
        errors:
          type: array
          items:
            "$ref": "#/components/schemas/GenericError"
          description: A list of related errors
        stack:
          type: string
          description: The stack trace (only in development mode)
      required:
      - name
      - message
      - status
    GenericError:
      type: object
      properties:
        name:
          type: string
          description: The error name
          minLength: 1
        message:
          type: string
          description: An error message
          minLength: 1
      additionalProperties: true
      required:
      - name
      - message
    Unauthorized:
      type: object
      properties:
        name:
          type: string
          description: The error name
          minLength: 1
          example: UNAUTHORIZED
          default: UNAUTHORIZED
        message:
          type: string
          description: An error message
          minLength: 1
        status:
          type: number
          description: The status code of the exception
          example: 401
          default: 401
        errors:
          type: array
          items:
            "$ref": "#/components/schemas/GenericError"
          description: A list of related errors
        stack:
          type: string
          description: The stack trace (only in development mode)
      required:
      - name
      - message
      - status
    NotFound:
      type: object
      properties:
        name:
          type: string
          description: The error name
          minLength: 1
          example: NOT_FOUND
          default: NOT_FOUND
        message:
          type: string
          description: An error message
          minLength: 1
        status:
          type: number
          description: The status code of the exception
          example: 404
          default: 404
        errors:
          type: array
          items:
            "$ref": "#/components/schemas/GenericError"
          description: A list of related errors
        stack:
          type: string
          description: The stack trace (only in development mode)
      required:
      - name
      - message
      - status
    ProfileModel:
      type: object
      properties:
        profile:
          type: array
          uniqueItems: true
          items:
            "$ref": "#/components/schemas/Profile"
    Profile:
      type: object
      properties:
        bio:
          type: string
          minLength: 3
        name:
          type: string
          minLength: 3
security:
- apiKey: []
paths:
  "/v1/profile/{did}":
    get:
      operationId: profileEndpointsGetProfileByDid
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ProfileModel"
        '401':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Unauthorized"
          description: Unauthorized. Request not authenticated, API token is missing,
            invalid or expired.
        '403':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Forbidden"
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/NotFound"
          description: Endpoint Not found
      summary: Gets a Profile via its 3ID
      parameters:
      - in: path
        name: did
        required: true
        schema:
          type: string
      tags:
      - Profile Endpoints
  "/v1/profile/address/{address}":
    get:
      operationId: profileEndpointsGetProfileByAddress
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ProfileModel"
        '401':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Unauthorized"
          description: Unauthorized. Request not authenticated, API token is missing,
            invalid or expired.
        '403':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Forbidden"
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/NotFound"
          description: Endpoint Not found
      summary: Gets a Profile via its linked Eth Address
      parameters:
      - in: path
        name: address
        required: true
        schema:
          type: string
      tags:
      - Profile Endpoints
  "/v1/profile/byTwitter/{twitterHandle}":
    get:
      operationId: profileEndpointsGetProfileByTwitter
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ProfileModel"
        '401':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Unauthorized"
          description: Unauthorized. Request not authenticated, API token is missing,
            invalid or expired.
        '403':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Forbidden"
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/NotFound"
          description: Endpoint not found
      summary: Gets a profile vis its linked twitter account
      parameters:
      - in: path
        name: twitterHandle
        required: true
        schema:
          type: string
      tags:
      - Profile Endpoints
tags:
- name: Profile Endpoints